name: ci-python-workflow
on: [push, pull_request]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Start stack (detached)
        run: docker compose -f docker-compose.yml up -d
      - name: create table in localstack
        run: python infra/create_table.py
      - name: Run tests
        run: pytest -v -s
      - name: Teardown
        if: always()
        run: docker compose down -v --remove-orphans